// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pcnt_loop
NumericVector pcnt_loop(NumericVector pop, NumericVector var, int p, double cp);
RcppExport SEXP _SocEpi_pcnt_loop(SEXP popSEXP, SEXP varSEXP, SEXP pSEXP, SEXP cpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pop(popSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type var(varSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type cp(cpSEXP);
    rcpp_result_gen = Rcpp::wrap(pcnt_loop(pop, var, p, cp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SocEpi_pcnt_loop", (DL_FUNC) &_SocEpi_pcnt_loop, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SocEpi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
